import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import http from 'http';
import type { AddressInfo } from 'net';
import express from 'express';

// Redirect DATA_DIR / LIBRARY_DIR before any server module loads (paths.ts
// captures them at import time). Mirrors telescopeObjectTraversal.test.ts.
// NOTE: a dot-free temp root on purpose. Express's res.sendFile goes through
// the `send` module, which applies its dotfile rule to the WHOLE path, so a
// DATA_DIR under the repo's `.test-tmp/` makes every sendFile answer 404
// regardless of whether the file exists. That artefact, not the route, is why
// the thumbnail happy path has no coverage today.
const TEST_DATA_DIR = vi.hoisted(() => {
  const _fs = require('fs') as typeof import('fs');
  const _os = require('os') as typeof import('os');
  const _path = require('path') as typeof import('path');
  const dir = _fs.mkdtempSync(_path.join(_os.tmpdir(), 'nebulis-thumbnail-safety-'));
  process.env.DATA_DIR = dir;
  return dir;
});

import fs from 'fs';
import path from 'path';
import { apiEnvelope } from '../../server/middleware/apiEnvelope';
import { libraryRouter } from '../../server/routes/library';
import db from '../../server/lib/db';
import { LIBRARY_DIR } from '../../server/lib/paths';

/**
 * HIGH 2, from auditreport.md: `GET /library/objects/:objectId/thumbnail` is a
 * PUBLIC route (middleware/auth.ts bypass list) that used to `unlinkSync` its
 * source whenever sharp reported a corrupt or unknown format. The source is
 * whatever `resolveObjectImagePath` selected, which can be the shared catalog
 * master in the sky cache as easily as one user's gallery image, so a single
 * unauthenticated GET could destroy bytes on disk — and a truncated-but-
 * recoverable image is exactly the case that reaches that branch.
 *
 * Uses a REAL truncated JPEG so sharp fails with its genuine
 * "Input file has corrupt header" message rather than a stub, and asserts the
 * source file is still on disk, byte for byte, after the request.
 */
const OBJECT_ID = 'M31';
const GALLERY_REL = `${OBJECT_ID}/gallery_${OBJECT_ID}.jpg`;

/** A JPEG SOI + APP0 header followed by garbage: sharp reports a corrupt header. */
function corruptJpeg(): Buffer {
  return Buffer.concat([
    Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00]),
    Buffer.alloc(50, 0x7f),
  ]);
}

let server: http.Server;
let baseUrl: string;
let sourceAbs = '';
let sourceBytes: Buffer;

beforeAll(async () => {
  fs.mkdirSync(path.join(LIBRARY_DIR, OBJECT_ID), { recursive: true });
  sourceAbs = path.join(LIBRARY_DIR, OBJECT_ID, `gallery_${OBJECT_ID}.jpg`);
  sourceBytes = corruptJpeg();
  fs.writeFileSync(sourceAbs, sourceBytes);

  db.prepare(
    'INSERT OR IGNORE INTO libraryObjects (objectId, folderName, fileCount, lastImport) VALUES (?, ?, 1, ?)',
  ).run(OBJECT_ID, OBJECT_ID, new Date().toISOString());
  // userSet = 1 so resolveObjectImagePath takes the user-gallery branch.
  db.prepare('UPDATE libraryObjects SET galleryImage = ?, galleryImageUserSet = 1 WHERE objectId = ?')
    .run(GALLERY_REL, OBJECT_ID);

  const app = express();
  app.use(express.json());
  app.use(apiEnvelope);
  // Deliberately NO auth middleware: this route is on the public bypass list,
  // so an unauthenticated request is the realistic (and worst) case.
  app.use((req, _res, next) => { req.id = 'test-request'; req.userId = null; req.userRole = 'viewer'; next(); });
  app.use('/', libraryRouter);

  server = http.createServer(app);
  await new Promise<void>(resolve => server.listen(0, resolve));
  const { port } = server.address() as AddressInfo;
  baseUrl = `http://127.0.0.1:${port}`;
});

afterAll(async () => {
  await new Promise<void>(resolve => server.close(() => resolve()));
  fs.rmSync(TEST_DATA_DIR, { recursive: true, force: true });
});

describe('GET /objects/:objectId/thumbnail never deletes its source', () => {
  it('leaves an undecodable gallery image on disk after a 404', async () => {
    const res = await fetch(`${baseUrl}/objects/${OBJECT_ID}/thumbnail?w=64&h=64`);
    expect(res.status).toBe(404);

    // The whole point: the bytes are still there, unchanged.
    expect(fs.existsSync(sourceAbs)).toBe(true);
    expect(fs.readFileSync(sourceAbs).equals(sourceBytes)).toBe(true);
  });

  it('is idempotent: a second request still 404s and still changes nothing', async () => {
    const res = await fetch(`${baseUrl}/objects/${OBJECT_ID}/thumbnail?w=64&h=64`);
    expect(res.status).toBe(404);
    expect(fs.readFileSync(sourceAbs).equals(sourceBytes)).toBe(true);
  });

  it('still serves a real, decodable image', async () => {
    // Guard against the fix over-reaching: a good source must still render.
    // The fixture is generated by sharp itself so it is guaranteed decodable
    // (a hand-copied PNG blob decoded metadata but failed resize).
    const sharp = (await import('sharp')).default;
    const otherId = 'M42';
    fs.mkdirSync(path.join(LIBRARY_DIR, otherId), { recursive: true });
    await sharp({ create: { width: 4, height: 4, channels: 3, background: { r: 10, g: 20, b: 30 } } })
      .jpeg()
      .toFile(path.join(LIBRARY_DIR, otherId, `gallery_${otherId}.jpg`));
    db.prepare(
      'INSERT OR IGNORE INTO libraryObjects (objectId, folderName, fileCount, lastImport) VALUES (?, ?, 1, ?)',
    ).run(otherId, otherId, new Date().toISOString());
    db.prepare('UPDATE libraryObjects SET galleryImage = ?, galleryImageUserSet = 1 WHERE objectId = ?')
      .run(`${otherId}/gallery_${otherId}.jpg`, otherId);

    const res = await fetch(`${baseUrl}/objects/${otherId}/thumbnail?w=64&h=64`);
    expect(res.status).toBe(200);
    expect(res.headers.get('content-type')).toBe('image/jpeg');
  });
});
